-- 코드를 입력하세요
SELECT R.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, 
    ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RI
JOIN REST_REVIEW R ON R.REST_ID = RI.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY R.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC;