-- 코드를 입력하세요
SELECT 
    YEAR(S.SALES_DATE) AS years,
    MONTH(S.SALES_DATE) AS months,
    U.GENDER,
    COUNT(DISTINCT U.USER_ID) AS users
FROM USER_INFO U
JOIN ONLINE_SALE S ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY years, months, U.GENDER
ORDER BY years, months, U.GENDER
