-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, 
    SUM (FP.PRICE*FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE PRODUCE_DATE >='2022-05-01' AND
    PRODUCE_DATE < '2022-06-01'
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID