-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
JOIN ICECREAM_INFO ON ICECREAM_INFO.FLAVOR = FIRST_HALF.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > '3000' 
AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY ICECREAM_INFO.INGREDIENT_TYPE DESC;