-- 코드를 작성해주세요
SELECT M.SCORE, M.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
JOIN
(SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE 
WHERE YEAR = 2022
GROUP BY EMP_NO) AS M
ON E.EMP_NO = M.EMP_NO
ORDER BY M.SCORE DESC
LIMIT 1